### ISSUE TITLE
Postgre error on heroku

### ISSUE THREAD

**Issue by Nhacsam** [Gollwu/LoLManager#53]
I have error with the database in the production environment. It seems that the database is on Amazon Web Services and have the app have problem to establish an SSL connection with it.

What tuto did you follow to setup the database ?

The error log is : 

```
Possibly unhandled SequelizeConnectionError: no pg_hba.conf entry for host "XXX.XXX.XXX.XXX", user "user", database "db", SSL off
           at /tmp/build_5f2eca2a9034d79c76332d9c2fde268e/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:73:20
           at null.<anonymous> (/tmp/build_5f2eca2a9034d79c76332d9c2fde268e/node_modules/pg/lib/client.js:171:5)
           at emit (events.js:107:17)
           at Socket.<anonymous> (/tmp/build_5f2eca2a9034d79c76332d9c2fde268e/node_modules/pg/lib/connection.js:109:12)
           at Socket.emit (events.js:107:17)
           at readableAddChunk (_stream_readable.js:163:16)
           at Socket.Readable.push (_stream_readable.js:126:10)
           at TCP.onread (net.js:538:20)
```

**Comment by Gollwu** [comment]
Did you take the credentials for the databse?

You can find them on heroku

**Comment by Gollwu** [comment]
Can't do it here, I'll upload the config.js file on the serve rdirectly tonight and we'll see

**Comment by Nhacsam** [comment]
Yeah I took the right credentials (I had trouble to do it), it's an other problem . I use the ones in the environment variable.
I obviously changed the credetials before copying the error on github.

**Comment by Gollwu** [comment]
user "user", database "db" ...

Are you sure?

**Comment by Nhacsam** [comment]
"I obviously changed the credetials before copying the error on github."
Look in the log in heroku if you have a doubt

**Comment by Gollwu** [comment]
It seemed to be a problem with the database not working with SSL. I tried to add ?ssl=true at the end of the conf string but it didn't change much

**Comment by Gollwu** [comment]
I'll investigate more this week end

**Comment by Gollwu** [comment]
I tried to add a conf file por Postgre adding this line 

host    db user address          md5 

which should allow the connections but it did not work

Also tried with host all all address trust

which sould allow everything but didn't work too.

Maybe it doesn't find the file, I put it on the root of the project
